### PR TITLE
Calculate button fix and Improved efficiency

### PR DESCRIPTION
**Pull request by nikhil-amin**
- Fix for issue "Calculate button not working unless length slider is changed"
- Improved efficiency by replacing multiple If statements with Switch cases

Fixes #(issue_no)

- [ ] Issue_no: ```<insert your issue no here>```
- [x] Not applicable 

## Type of change

Choosing one or more options from the following as per the nature of your Pull request.

- [ ] New project insert
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation Update

# Checklist:
Please tick all the boxes that are fulfilled by your Pull Request.

- [x] I have named my files and folder, according to this project's guidelines.
- [x] My code follows the style guidelines of this project.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have created a helpful and easy to understand `README.md`, according to the given [`README_TEMPLATE.`](https://github.com/nduongthucanh/python-mini-project/blob/master/README_TEMPLATE.md)
- [x] My changes do not produce any warnings.

### CODE REVIEW

**Comment by Harsh151200** [comment]
That's great

**Comment by nikhil-amin** [comment]
Hey bro, thanks for the merge. Can you please add **hacktoberfest-accepted** label on this PR?

**Comment by Harsh151200** [comment]
Yes added!!

**Comment by nikhil-amin** [comment]
Thanks

**Pull request merged**
